### ISSUE TITLE
Problema al intentar depositar un cheque

### ISSUE THREAD

**Issue by andres53016** [tryton-ar/account_check_ar#7]
Cuando intento depositar un cheque surge el siguiente error:

> Traceback (most recent call last):
>   File "/trytond/wsgi.py", line 71, in dispatch_request
>     return endpoint(request, **request.view_args)
>   File "/trytond/protocols/dispatcher.py", line 41, in rpc
>     request, database_name, *request.rpc_params)
>   File "/trytond/wsgi.py", line 42, in auth_required
>     return wrapped(*args, **kwargs)
>   File "/trytond/protocols/wrappers.py", line 122, in wrapper
>     return func(request, pool, *args, **kwargs)
>   File "/trytond/protocols/dispatcher.py", line 167, in _dispatch
>     result = rpc.result(meth(*c_args, **c_kwargs))
>   File "/trytond/wizard/wizard.py", line 287, in execute
>     return wizard._execute(state_name)
>   File "/trytond/wizard/wizard.py", line 318, in _execute
>     result = self._execute(transition())
>   File "/trytond/modules/account_check_ar/account_check_ar.py", line 436, in transition_deposit
>     'state': 'deposited',
>   File "/trytond/model/modelsql.py", line 996, in write
>     where=red_sql))
>   File "/trytond/backend/postgresql/database.py", line 61, in execute
>     cursor.execute(self, sql, args)
> IntegrityError: insert or update on table "account_third_check" violates foreign key constraint "account_third_check_account_bank_out_fkey"
> DETAIL:  Key (account_bank_out)=(1) is not present in table "account_party_bank".
>

**Comment by lukio** [comment]
Hola @andres53016, por lo que veo tu modelo esta relacionado a un módulo (account_party_bank) que ya no se usa y fue removido luego de la versión 3.8[0]

[0] https://github.com/tryton-ar/account_check_ar/commit/57c82bcd69900b399c8ea2fc698286ba970ade76#diff-c934463fb4d1bc0878ff4087a3da8c6cL151

Te recomiendo borrar la foreing key manualmente.
